title: DIY Biosphere
email: diy@biosphere.com
description: Hello mate
baseurl: ""
url: "danipy.github.io" # the base hostname & protocol for your site
permalink: /groups/:title
twitter_username: mellamodaniel_1
github_username: cube5

# Where things are
source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir: ./_data
collections: null

# Outputting
paginate_path: /page:num
timezone: null
